### PR TITLE
Use commerce framework

### LINKED ISSUE #4: Match the data required by Next.js Commerce
The current state of the project requires heavy changes to the `commerce` codebase. Need to update the return type of the APIs and hooks so  this module can be a straight drop into `commerce` without any changes to your existing project.

### LINKED ISSUE #161: Provider: Shopify
## Provider: Shopify
Ecomerce Provider: https://www.shopify.com/
Assigned to: @petermekhaeil

### PR DESCRIPTION
**Pull request by petermekhaeil**
Opening this Pull Request to welcome contributors to help out.

The current state of this provider requires modifications to your application to work. This PR modifies the existing APIs, hooks and file/folder structures to follow the guidelines of [commerce-framework](https://github.com/vercel/commerce-framework).

The goal is to move this provider into [commerce/framework](https://github.com/vercel/commerce/tree/master/framework) when it's ready.

**Status**

- [x]  Move everything into `shopify` folder to prepare to move into [`framework`](https://github.com/vercel/commerce/tree/master/framework) folder.
- [x] CommerceProvider
- [x] API Operations - Get all collections
- [x] API Operations - Get all pages
- [x] API Operations - Get all product paths
- [x] API Operations - Get all products
- [ ] API Operations - Get page
- [x] API Operations - Get product
- [ ] API Operations - Get Site Info
- [x] Hook - Add Item
- [x] Hook - Remove Item
- [x] Hook - Update Item
- [ ] Hook - Get Cart
- [ ] Redirect `/checkout` to Shopify checkout page.
- [ ] Remove dependency on `shopify-js-buy` (See https://github.com/petermekhaeil/nextjs-commerce-shopify/issues/3)
- [ ] Typing
- [ ] Tests
- [ ] Remove everything that is outside of `shopify` folder.

Closes #4.
Resolves https://github.com/vercel/commerce/issues/161.

### CODE REVIEW

**Comment by LarsBuur** [comment]
I would like to participate in your efforts. What´s the best way to have https://github.com/vercel/commerce running locally with your new and shiny shoify provider.

**Comment by petermekhaeil** [comment]
> I would like to participate in your efforts. What´s the best way to have https://github.com/vercel/commerce running locally with your new and shiny shoify provider.

I have updated the [README.md](https://github.com/petermekhaeil/nextjs-commerce-shopify/blob/use-commerce-framework/README.md) on how to get this going in a fresh copy of Next.js Commerce. Do let me know if I missed a step in the installation / happy to receive feedback.

**Comment by daniel7912** [comment]
Hi @petermekhaeil great work so far! I was just wondering if you are planning to add in the auth features like the BigCommerce package has? I don't think it's in the Shopify Buy SDK but you can get customer tokens via their GraphQL API. Thanks.

**Comment by petermekhaeil** [comment]
> Hi @petermekhaeil great work so far! I was just wondering if you are planning to add in the auth features like the BigCommerce package has? I don't think it's in the Shopify Buy SDK but you can get customer tokens via their GraphQL API. Thanks.

Sorry, auth and customer details are not on my radar. I'm focused on the cart and product catalog. 

This repo is open for all contributions though - would appreciate anyone wishing to help out and speed things up. Thank you!

**Comment by LarsBuur** [comment]
Thank you @petermekhaeil  for your hard work. I am lurking in the shades and looking to get my feet wet.

**Comment by petermekhaeil** [comment]
I've moved this PR over to `vercel/commerce` for the Vercel team + community to continue building on top of what I have.: https://github.com/vercel/commerce/pull/186

Master branch (v1.x) can be used and is ready for a production use case, but requires you to modify your Nextjs commerce app to use the APIs provided in the package. This is what I am using in production now for my shops. If you don't want to modify your app, follow the PR over at `vercel/commerce`.

Going to close this PR off. Hope to see you all over there to help out!

**Pull request closed without merging**
